server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  #路由的id，没有固定规则但是要求统一
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
            #- After=2022-02-16T17:43:27.502+08:00[Asia/Shanghai] #要在这个时间以后才能访问
            #- Before=2022-02-16T17:43:27.502+08:00[Asia/Shanghai] #要在这个时间之前才能访问
            #- Between=2022-02-16T17:55:27.502+08:00[Asia/Shanghai],2022-02-16T17:58:27.502+08:00[Asia/Shanghai] #要在这个时间之间才能访问
            #- Cookie=username,zhy #cookie限制
            #- Header=X-Request-Id,\d+ #请求头要存有X-Request-Id属性并且值为整数的正则表达式
        - id: payment_routh2  #路由的id
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**



eureka:
  instance:
    prefer-ip-address: true
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版


