server:
  port: 80

spring:
  application:
    name: cloud-order-service


eureka:
  client:
    register-with-eureka: true #表示是否向注册中心注册自己默认为true
    fetch-registry: true  #是否EurekaServer从抓紧已有的注册信息，默认为true。单节点无所谓，集群必须要设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true

#设置feign客户端超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.springcloud.service.PaymentFeignService: debug


