server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer1
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 47.100.187.127
                port: 5672
                username: zhy
                password: zhy

      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称的定义
          content-type: application/json #设置消息类型，本次为json，文本为application/text
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: steamA #解决重复问题


  rabbitmq:  #需要单独链接
    host: 47.100.187.127
    port: 5672
    username: zhy
    password: zhy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8802.com
    prefer-ip-address: true
